version: '3.8'
services:
  cache:
    container_name: cache-container
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes: 
      - cache:/data

  postgres:
    container_name: postgres-container
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: Ådmin123456789
    networks:
      - local-keycloak

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak-container
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-container
      DB_DATABASE: keycloak
      DB_USER: db_admin
      DB_PASSWORD: Ådmin123456789
      KEYCLOAK_ADMIN: Ådmin
      KEYCLOAK_ADMIN_PASSWORD: Ådmin123456789
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    ports:
      - "28080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak


volumes:
  cache:
    driver: local

networks:
  local-keycloak:
